project:
  type: book
  output-dir: docs



book:
  title: "Project template"
  author: "J Smith"
  date: "12/22/2023"
  downloads: pdf

  abstract: this is an abstract. Can you write an approx. ten sentence summary of your project? In one sentence what do you do (e.g. cryptography, analysis, numerical analysis, statistical modelling, optimisation etc.)? Why is this topic important? What is the key background? What re your Aims? What do you actually do? Final thought ...
  
  chapters:
    - index.qmd
    - intro.qmd   
    - ResultsChapter1.qmd 
    - summary.qmd
  appendices:
    - AIStatement.qmd 
    - Appendix1.qmd


bibliography: references.bib
degreetype: BSc XXX
affiliation: University of Dundee

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    toc: True
    template-partials:
        - "resources/title.tex"
    
    documentclass: scrreprt
    echo: false # This stops displaying the code that generates Python figures
    
execute:
  warning: false
     


  



