# Statement on use of AI in your project

 

## Statement of acknowledgement

Please include the statement that reflects how you have used any GAI tools:

1. No content generated by AI technologies has been presented as my own work.
2. I acknowledge the use of _______________ to generate materials for background research and self-study in the drafting of this assessment. 
3. I acknowledge the use of ______________ to structure or plan this assessment.
4. I acknowledge the use of ___________________ to generate materials that were included within my final assessment in modified form. 
5.I acknowledge the use of __________________________ to generate materials that were included in my final assessment in unmodified form. An example of this would be a quote or image produced by the AI output.



## Description of how information or material was generated

You must describe how the information or material was generated, what the output was and how the output was modified by you using the following format:

1. name of AI tool   
2. inputted prompts  
3. The output obtained was: (Paste the full output generated by the AI tool) 
4.  Explain how you adapted the output for use in your work:




 


